<?php
$CONFIG = array (
  'instanceid' => 'ocd551ea6ca7',
  'passwordsalt' => 'b996c5fa9ec08cc147e5c8b7448380',
  'trusted_domains' => 
  array (
    0 => 'cloud.uni-halle.de',
  ),
  'datadirectory' => '/var/www/owncloud-prod/oc-data',
  'skeletondirectory' => '/var/www/owncloud-prod/user-template',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'a6anv_owncloud_apache',
  'dbhost' => 'mysql.itz.uni-halle.de',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'a6anv',
  'dbpassword' => 'peggyg22',
  'theme' => 'mlu',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'loglevel' => '2',
  'maintenance' => false,
  'appstoreenabled' => false,
  'enable_avatars' => false,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Movie',
    5 => 'OC\\Preview\\MSOffice2003',
    6 => 'OC\\Preview\\MSOffice2007',
    7 => 'OC\\Preview\\MSOfficeDoc',
    8 => 'OC\\Preview\\OpenDocument',
    9 => 'OC\\Preview\\PDF',
    10 => 'OC\\Preview\\StarOffice',
    11 => 'OC\\Preview\\SVG',
  ),
  'overwrite.cli.url' => 'https://cloud.uni-halle.de',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'secret' => '0e33529c14aeb21930d6180aae56d69fbc1e15c89d27b62d643133aa4b2d9570eed0139136b76d543cd4c8ce4be986ab',
  'config_is_read_only' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'uni-halle.de',
);
